language: r
cache: packages
latex: false
fortran: false
pandoc: false

r_check_args: '--run-donttest'

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - dist: xenial
      addons:
        apt:
          sources:
          - sourceline: 'ppa:cran/tesseract'
    - os: osx
      brew_packages: tesseract
    - os: osx
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    packages:
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - tesseract-ocr-fra
      - libpoppler-cpp-dev
      - libmagick++-dev
